#!/bin/bash

MY_PATH="$HOME/ponpontools/etc"

# ヘルプ出力関数
usage(){
    cat << _EOS_
    Usage:
        $(basename $0) [-f] <-f file discriptor> int
        $(basename $0) <-h|--help>
_EOS_
}

# オプション解析で使う変数の初期化
DATA=""
OPTS=$(getopt -o "f:h" -l "help" -- "$@")
[ $? -ne 0 ] && usage >&2 && exit 1
eval set -- "$OPTS"
while :; do
    case "$1" in
    '-f') DATA=$2; shift 2;;
    '--') shift; break;;
    '-h'|'--help')usage; exit 0;;
    *) echo "[error] illegal option" >&2; usage >&2; exit 1;;
    esac
done

# 必須オプションの確認
[ -z "$DATA" ] && echo "[error] missing option '-f'" >&2 && usage >&2 && exit 1

sed -ie "s/lea\sebx,\s\[edx+.\]/lea ebx, \[edx+$DATA\]/" $MY_PATH/dup2.s
gcc -nostdlib -m32 $MY_PATH/dup2.s -o $MY_PATH/tmp.out
RESULT=$(objdump -M intel -d $MY_PATH/tmp.out | grep '^ ' | cut -f2 | perl -pe 's/(\w{2})\s+/\\x\1/g')
echo $RESULT
rm -f $MY_PATH/tmp.out
